function variables = mem_min_vars

variables = {...
    'fixWindowEntered',...
    'targOn',...
    'responseCueOn',...
    'responseOnset',...
    'toneOn',...
    'rewardOn',...
    'trialOutcome',...
    'saccToTargIndex',...
    'targAngle',...
    'saccAngle',...
    'spikeData',...
    'SessionData',...
    };